name = new_flowers
description = In development, this mod aims to bring more flowers to the base game, and new ways to interact with them. So far it adds dandelions to the game without any functionality, but more is planned.
depends = default
optional_depends = 
min_minetest_version = 5.0
